### ISSUE TITLE
USER STORY: Navigate the site

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Salon#11]
As a **user** I can **navigate around the site using links in a navbar** so that **I can easily access any area of the site I wish to see**

---

**Acceptance Criteria**
- Navbar appears on all site pages
- Site Logo takes user to homepage
- Navbar links take user to expected page
- Navbar links are well organised with dropdowns if necessary
- Navbar is responsive and links stay visible and usable on all screen sizes

**Tasks**
- [x] Create Nav element in base.html
- [x] Import Bootstrap responsive nav element
- [x] Add links to all site page URLs
- [x] Organise links into groups with Bootstrap dropdowns
---

**EPIC** 
- #5
