### ISSUE TITLE
USER STORY: Purchase ticket

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Salon#16]
As a **user**, I want **to purchase tickets for a selected salon** so that **I can reserve my spot.**

---

**Acceptance Criteria**

- Registered users can select an event and proceed to checkout, receiving confirmation emails.	

**Tasks**

- [x] Create checkout page
- [x] Implement payment processing options
- [x] Set up confirmation emails

---
**EPIC #8**
