### ISSUE TITLE
USER STORY: Email confirmation after checkout

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Salon#29]
As a **Site user** I want **to receive an email confirmation after checking out** so that **I can save and keep a record of what I have purchased**

---

**Acceptance Criteria**
- [x] An email confirmation is sent to the user’s registered email after successful checkout.
- [x] The email includes order number, purchase date, item list, total amount, date & time of event, meeting link to event, and info on how to get in contact. 
- [x] The email must be sent immediately upon order confirmation.

**Tasks**
- [x] Create a template with required information.
- [x] Develop backend logic to trigger emails.
- [x] Integrate Email Service

**Test Email Process**
- [x] Ensure emails are sent correctly and contain accurate information.

---
**Epic**
- #7
