### ISSUE TITLE
USER STORY: Add an event to the store

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Salon#30]
As a **Store owner** I want **to a add an event ** so that **I can update my store**

---

**Acceptance Criteria**

- Add new events to the store
- Change price, description, image, date, host of event
 
**Future development**
- Available tickets 
- Remove events that are no longer for sale

**Tasks**
- [x]  set up product management 
- [x]  set up django admin

**Testing**
  - [x] Conduct unit tests to ensure all functionalities work as expected.
  - [x] Perform user acceptance testing to validate the user experience.

---
**Epic**
- #6
