### ISSUE TITLE
USERSTORY: FAQ

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Salon#32]
As a **Site user** I want ** answers on common questions** so that **I don't have to ask and wait for answers on all questions I may have on how to use the site**

---

**Acceptance Criteria**

- [x] pick a question
- [x] get an answer

**Tasks**
- [x] add app to setting
- [x] add url and path
- [x] add model
- [x] migrate to create the faq models.
- [x] add template

---
**Epic**
- #33
