### ISSUE TITLE
USERSTORY: About the site

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Salon#34]
As a **Site user** I want **to know what the site is about and who is behind it ** so that **I know if the site is right for me**

---

**Acceptance Criteria**

- [x] Information/description of the site
- [x] contact form

**Tasks**
- [x] add app
- [x] add url and path
- [x] add model
- [x] migrate to create the model
- [x] add views
- [x] add template

---
**Epic**
- #33
