### ISSUE TITLE
USERSTORY: Newsletter

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Salon#36]
As a **Site user** I want **to be able to sign up for a newsletter** so that **I can get tips and offers on new Salon Talks**

---

**Acceptance Criteria**

- [x] Signup form 
- [x] Verification  of successful registration

**Tasks**
- [x] add form with email signup field. 
- [x] add newsletter signup in navigation

---
**Epic**
- #33
