### ISSUE TITLE
TASK: SEO

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Salon#40]
**Tasks** 
- [x] List and validate keywords
- [x] Create short tail keywords
- [x] Create longtail keywords
- [x] SEO implementation in html
- [x] Other 

**Epic**
- #45
