### ISSUE TITLE
USERSTORY: Contact management

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Salon#44]
As a **Site Administrator** I want **to be able to manage contact requests on the Salon Talks site** so that ** I don't have to leave the site to respond**

---

**Acceptance Criteria**

-  I must be able to navigate back to the contact list easily.
- Responded contacts should be checked to indicate they have been responded to.

**Tasks**
- [x] create a user-friendly interface for the Site Administrator to view and manage contact requests.
- [x] Ensure there is a clear and accessible way to navigate back to the contact list from the contact request detail view.
- [x] Implement a feature that allows the Site Administrator to respond to contact requests directly within the site.
- [x] Add functionality to automatically check off or mark contacts as responded once a reply has been sent.

**Testing**
   - Test Navigation and Response Features
   - Test that responded contacts are correctly indicated.
  
---
**Epic**
- #33
